// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adjPairsWithId
List adjPairsWithId(IntegerVector cells, IntegerVector id, int numCol, int numCell, int directions);
RcppExport SEXP _SpaDES_tools_adjPairsWithId(SEXP cellsSEXP, SEXP idSEXP, SEXP numColSEXP, SEXP numCellSEXP, SEXP directionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cells(cellsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< int >::type numCol(numColSEXP);
    Rcpp::traits::input_parameter< int >::type numCell(numCellSEXP);
    Rcpp::traits::input_parameter< int >::type directions(directionsSEXP);
    rcpp_result_gen = Rcpp::wrap(adjPairsWithId(cells, id, numCol, numCell, directions));
    return rcpp_result_gen;
END_RCPP
}
// adjPairsMatrix
IntegerMatrix adjPairsMatrix(IntegerVector cells, int numCol, int numCell, int directions, Rcpp::Nullable<IntegerVector> state);
RcppExport SEXP _SpaDES_tools_adjPairsMatrix(SEXP cellsSEXP, SEXP numColSEXP, SEXP numCellSEXP, SEXP directionsSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cells(cellsSEXP);
    Rcpp::traits::input_parameter< int >::type numCol(numColSEXP);
    Rcpp::traits::input_parameter< int >::type numCell(numCellSEXP);
    Rcpp::traits::input_parameter< int >::type directions(directionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<IntegerVector> >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(adjPairsMatrix(cells, numCol, numCell, directions, state));
    return rcpp_result_gen;
END_RCPP
}
// duplicatedInt
LogicalVector duplicatedInt(IntegerVector x);
RcppExport SEXP _SpaDES_tools_duplicatedInt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(duplicatedInt(x));
    return rcpp_result_gen;
END_RCPP
}
// allInRange01
bool allInRange01(NumericVector x);
RcppExport SEXP _SpaDES_tools_allInRange01(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(allInRange01(x));
    return rcpp_result_gen;
END_RCPP
}
// runifC
NumericVector runifC(const int N);
RcppExport SEXP _SpaDES_tools_runifC(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(runifC(N));
    return rcpp_result_gen;
END_RCPP
}
// spreadCppEngine
List spreadCppEngine(int numCol, int numCell, int directions, IntegerVector loci, NumericVector spreadProb, NumericVector maxSize, NumericVector minSize, double iterations, int jumpTries, double jumpMeanDist, int minSizeTries);
RcppExport SEXP _SpaDES_tools_spreadCppEngine(SEXP numColSEXP, SEXP numCellSEXP, SEXP directionsSEXP, SEXP lociSEXP, SEXP spreadProbSEXP, SEXP maxSizeSEXP, SEXP minSizeSEXP, SEXP iterationsSEXP, SEXP jumpTriesSEXP, SEXP jumpMeanDistSEXP, SEXP minSizeTriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type numCol(numColSEXP);
    Rcpp::traits::input_parameter< int >::type numCell(numCellSEXP);
    Rcpp::traits::input_parameter< int >::type directions(directionsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type loci(lociSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spreadProb(spreadProbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type maxSize(maxSizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minSize(minSizeSEXP);
    Rcpp::traits::input_parameter< double >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type jumpTries(jumpTriesSEXP);
    Rcpp::traits::input_parameter< double >::type jumpMeanDist(jumpMeanDistSEXP);
    Rcpp::traits::input_parameter< int >::type minSizeTries(minSizeTriesSEXP);
    rcpp_result_gen = Rcpp::wrap(spreadCppEngine(numCol, numCell, directions, loci, spreadProb, maxSize, minSize, iterations, jumpTries, jumpMeanDist, minSizeTries));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpaDES_tools_adjPairsWithId", (DL_FUNC) &_SpaDES_tools_adjPairsWithId, 5},
    {"_SpaDES_tools_adjPairsMatrix", (DL_FUNC) &_SpaDES_tools_adjPairsMatrix, 5},
    {"_SpaDES_tools_duplicatedInt", (DL_FUNC) &_SpaDES_tools_duplicatedInt, 1},
    {"_SpaDES_tools_allInRange01", (DL_FUNC) &_SpaDES_tools_allInRange01, 1},
    {"_SpaDES_tools_runifC", (DL_FUNC) &_SpaDES_tools_runifC, 1},
    {"_SpaDES_tools_spreadCppEngine", (DL_FUNC) &_SpaDES_tools_spreadCppEngine, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpaDES_tools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
